apiVersion: v1
kind: Service
metadata:
  namespace: process-iee
  name: iee
spec:
  type: NodePort
  selector:
    app: iee-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
---
apiVersion: v1
kind: Pod
metadata:
  namespace: process-iee
  name: iee
  labels:
    app: iee-app
spec:
  containers:
  - name: iee
    image: cyfronet/iee
    env:
      - name: DB_PASS
        value: zaq12wsx
    ports:
    - containerPort: 3000
