apiVersion: v1
kind: Service
metadata:
  namespace: process-iee
  name: db
spec:
  selector:
    app: psql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Pod
metadata:
  namespace: process-iee
  name: psql
  labels:
    app: psql
spec:
  containers:
  - name: postgres
    image: postgres
    env:
      - name: POSTGRES_PASSWORD
        value: zaq12wsx
    ports:
    - containerPort: 5432
