---
- hosts: all
  become: true
  tasks:
  - name: Copy slurm deployment file
    copy:
        src: ./slurm.yaml
        dest: /home/vagrant/slurm.yaml

  - name: Create slurm namespace
    become: False
    command: kubectl create ns process-slurm

  - name: Wait 5s
    become: False
    command: sleep 5

  - name: Deploy slurm cluster
    become: False
    command: kubectl create -f slurm.yaml

  - name: Wait for slurm cluster up
    become: False
    command: kubectl wait -n process-slurm --for=condition=Ready pod/core-slurm --timeout=360s
